#pragma once
#include <raylib.h>

#define SPACEGRAY CLITERAL(Color){ 28, 26, 41, 255 }
#define LIFELESSNEBULA CLITERAL(Color){ 75, 78, 94, 255 }
#define HAUNTINGWHITE CLITERAL(Color){ 148, 150, 166, 255 }
#define GLEEFULDUST CLITERAL(Color){ 116, 125, 237, 255 }
#define INTERFERENCEGRAY CLITERAL(Color){ 232, 234, 255, 255 }
#define REDSTONE CLITERAL(Color){ 212, 25, 25, 255 }
#define DESTRUCTIVERED CLITERAL(Color){ 219, 18, 18, 255 }
#define DEADCABLE CLITERAL(Color){ 122, 118, 118, 255 }
#define INPUTLAVENDER CLITERAL(Color){ 128, 106, 217, 255 }
#define OUTPUTAPRICOT CLITERAL(Color){ 207, 107, 35, 255 }
#define WIPBLUE CLITERAL(Color){ 26, 68, 161, 255 }
#define CAUTIONYELLOW CLITERAL(Color){ 250, 222, 37, 255 }

extern Color uiColors[18];
enum class UIColorID : unsigned
{
    UI_COLOR_BACKGROUND, // BLACK
    UI_COLOR_BACKGROUND1, // SPACEGRAY
    UI_COLOR_BACKGROUND2, // LIFELESSNEBULA
    UI_COLOR_BACKGROUND3, // GLEEFULDUST
    UI_COLOR_FOREGROUND3, // DEADCABLE
    UI_COLOR_FOREGROUND2, // HAUNTINGWHITE
    UI_COLOR_FOREGROUND1, // INTERFERENCEGRAY
    UI_COLOR_FOREGROUND, // WHITE
    UI_COLOR_INPUT, // INPUTLAVENDER
    UI_COLOR_OUTPUT, // OUTPUTAPRICOT
    UI_COLOR_AVAILABLE, // WIPBLUE
    UI_COLOR_INTERACT, // YELLOW
    UI_COLOR_ACTIVE, // REDSTONE
    UI_COLOR_ERROR, // MAGENTA
    UI_COLOR_DESTRUCTIVE, // DESTRUCTIVERED
    UI_COLOR_SPECIAL, // VIOLET
    UI_COLOR_CAUTION, // CAUTIONYELLOW
    UI_COLOR_BLUEPRINTS_BACKGROUND, // (literal)
};

Color& UIColor(UIColorID id);
