#pragma once
#include <raylib.h> 

namespace ui_color
{
    constexpr Color SPACEGRAY{ 28, 26, 41, 255 };
    constexpr Color LIFELESSNEBULA{ 75, 78, 94, 255 };
    constexpr Color HAUNTINGWHITE{ 148, 150, 166, 255 };
    constexpr Color GLEEFULDUST{ 116, 125, 237, 255 };
    constexpr Color INTERFERENCEGRAY{ 232, 234, 255, 255 };
    constexpr Color REDSTONE{ 212, 25, 25, 255 };
    constexpr Color DESTRUCTIVERED{ 219, 18, 18, 255 };
    constexpr Color DEADCABLE{ 122, 118, 118, 255 };
    constexpr Color INPUTLAVENDER{ 128, 106, 217, 255 };
    constexpr Color OUTPUTAPRICOT{ 207, 107, 35, 255 };
    constexpr Color WIPBLUE{ 26, 68, 161, 255 };
    constexpr Color CAUTIONYELLOW{ 250, 222, 37, 255 };
}

extern Color uiColors[18];
enum class UIColorID : unsigned
{
    UI_COLOR_BACKGROUND, // BLACK
    UI_COLOR_BACKGROUND1, // SPACEGRAY
    UI_COLOR_BACKGROUND2, // LIFELESSNEBULA
    UI_COLOR_BACKGROUND3, // GLEEFULDUST
    UI_COLOR_FOREGROUND3, // DEADCABLE
    UI_COLOR_FOREGROUND2, // HAUNTINGWHITE
    UI_COLOR_FOREGROUND1, // INTERFERENCEGRAY
    UI_COLOR_FOREGROUND, // WHITE
    UI_COLOR_INPUT, // INPUTLAVENDER
    UI_COLOR_OUTPUT, // OUTPUTAPRICOT
    UI_COLOR_AVAILABLE, // WIPBLUE
    UI_COLOR_INTERACT, // YELLOW
    UI_COLOR_ACTIVE, // REDSTONE
    UI_COLOR_ERROR, // MAGENTA
    UI_COLOR_DESTRUCTIVE, // DESTRUCTIVERED
    UI_COLOR_SPECIAL, // VIOLET
    UI_COLOR_CAUTION, // CAUTIONYELLOW
    UI_COLOR_BLUEPRINTS_BACKGROUND, // (literal)
};

Color& UIColor(UIColorID id);
